//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckListManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListItem
    {
        public int Id { get; set; }
        public int CheckListId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    
        public virtual CheckList CheckList { get; set; }
    }
}
